/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollaborateRouteImport } from './routes/collaborate'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as DashboardSurveyAnalyticsRouteImport } from './routes/dashboard.survey-analytics'
import { Route as DashboardSponsorRouteImport } from './routes/dashboard.sponsor'
import { Route as DashboardSlotsRouteImport } from './routes/dashboard.slots'
import { Route as DashboardInvestRouteImport } from './routes/dashboard.invest'
import { Route as DashboardImpactRouteImport } from './routes/dashboard.impact'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'

const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateRoute = CollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardSurveyAnalyticsRoute =
  DashboardSurveyAnalyticsRouteImport.update({
    id: '/survey-analytics',
    path: '/survey-analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSponsorRoute = DashboardSponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSlotsRoute = DashboardSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestRoute = DashboardInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImpactRoute = DashboardImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => DashboardRoute,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/$artistId',
  path: '/$artistId',
  getParentRoute: () => ArtistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/collaborate': typeof CollaborateRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/dashboard/impact': typeof DashboardImpactRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/slots': typeof DashboardSlotsRoute
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/survey-analytics': typeof DashboardSurveyAnalyticsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/collaborate': typeof CollaborateRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/dashboard/impact': typeof DashboardImpactRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/slots': typeof DashboardSlotsRoute
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/survey-analytics': typeof DashboardSurveyAnalyticsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/collaborate': typeof CollaborateRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/dashboard/impact': typeof DashboardImpactRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/slots': typeof DashboardSlotsRoute
  '/dashboard/sponsor': typeof DashboardSponsorRoute
  '/dashboard/survey-analytics': typeof DashboardSurveyAnalyticsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/artists'
    | '/collaborate'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/signup'
    | '/survey'
    | '/artists/$artistId'
    | '/dashboard/impact'
    | '/dashboard/invest'
    | '/dashboard/slots'
    | '/dashboard/sponsor'
    | '/dashboard/survey-analytics'
    | '/events/$eventId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artists'
    | '/collaborate'
    | '/contact'
    | '/events'
    | '/login'
    | '/signup'
    | '/survey'
    | '/artists/$artistId'
    | '/dashboard/impact'
    | '/dashboard/invest'
    | '/dashboard/slots'
    | '/dashboard/sponsor'
    | '/dashboard/survey-analytics'
    | '/events/$eventId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/artists'
    | '/collaborate'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/login'
    | '/signup'
    | '/survey'
    | '/artists/$artistId'
    | '/dashboard/impact'
    | '/dashboard/invest'
    | '/dashboard/slots'
    | '/dashboard/sponsor'
    | '/dashboard/survey-analytics'
    | '/events/$eventId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  CollaborateRoute: typeof CollaborateRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SurveyRoute: typeof SurveyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborate': {
      id: '/collaborate'
      path: '/collaborate'
      fullPath: '/collaborate'
      preLoaderRoute: typeof CollaborateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/survey-analytics': {
      id: '/dashboard/survey-analytics'
      path: '/survey-analytics'
      fullPath: '/dashboard/survey-analytics'
      preLoaderRoute: typeof DashboardSurveyAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sponsor': {
      id: '/dashboard/sponsor'
      path: '/sponsor'
      fullPath: '/dashboard/sponsor'
      preLoaderRoute: typeof DashboardSponsorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/slots': {
      id: '/dashboard/slots'
      path: '/slots'
      fullPath: '/dashboard/slots'
      preLoaderRoute: typeof DashboardSlotsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invest': {
      id: '/dashboard/invest'
      path: '/invest'
      fullPath: '/dashboard/invest'
      preLoaderRoute: typeof DashboardInvestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/impact': {
      id: '/dashboard/impact'
      path: '/impact'
      fullPath: '/dashboard/impact'
      preLoaderRoute: typeof DashboardImpactRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
  }
}

interface ArtistsRouteChildren {
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface DashboardRouteChildren {
  DashboardImpactRoute: typeof DashboardImpactRoute
  DashboardInvestRoute: typeof DashboardInvestRoute
  DashboardSlotsRoute: typeof DashboardSlotsRoute
  DashboardSponsorRoute: typeof DashboardSponsorRoute
  DashboardSurveyAnalyticsRoute: typeof DashboardSurveyAnalyticsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardImpactRoute: DashboardImpactRoute,
  DashboardInvestRoute: DashboardInvestRoute,
  DashboardSlotsRoute: DashboardSlotsRoute,
  DashboardSponsorRoute: DashboardSponsorRoute,
  DashboardSurveyAnalyticsRoute: DashboardSurveyAnalyticsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  CollaborateRoute: CollaborateRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SurveyRoute: SurveyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
